/* The following code was generated by JFlex 1.6.1 */

package Analisis;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import Analisis.lexema;
import Utilidades.ErrorC;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>scanner.jflex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int comentarioSimple = 2;
  public static final int comentarioMulti = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  4, 57,  2,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1, 43, 10,  0,  0, 55, 48, 16, 50, 51, 11, 42,  0, 18,  6, 19, 
     5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 17, 49, 46, 44, 45, 52, 
     0, 35, 32, 33, 29, 23, 22, 37, 34, 21,  7, 41, 24,  7, 27, 30, 
    38,  7, 36, 26, 28, 31,  7, 39,  7,  7,  7,  0,  0,  0, 56,  7, 
     0, 35, 32, 33, 29, 23, 22, 37, 34, 21,  7, 41, 24,  7, 27, 30, 
    38,  7, 36, 26, 28, 31,  7, 39,  7,  7,  7, 53, 47, 54,  0,  0, 
     0,  0,  0,  0,  0, 57,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  9,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  9,  0,  0, 
     0,  9,  0,  9,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0, 
     0,  0, 12,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0, 12,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\2\1\1\6"+
    "\2\1\1\7\1\10\1\11\1\1\3\5\1\1\7\5"+
    "\1\12\1\13\1\14\1\15\1\16\2\1\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\27\5\0\1\31\1\0\1\32\1\33\1\0\1\33"+
    "\4\5\1\0\11\5\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\0\1\45\1\0\2\32"+
    "\2\46\1\47\1\5\1\0\1\5\1\0\7\5\1\0"+
    "\1\5\1\0\1\5\2\0\1\5\2\50\1\0\1\5"+
    "\1\51\1\5\1\52\2\5\1\53\1\0\1\5\1\0"+
    "\1\5\1\0\2\54\1\0\2\5\2\55\1\0\1\5"+
    "\1\0\1\5\2\56\1\0\2\57\1\60\1\0\1\5"+
    "\2\0\2\5\1\0\1\5\1\61\1\0\1\61\1\5"+
    "\2\62\1\0\1\5\2\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\256\0\256\0\350\0\u0122"+
    "\0\u015c\0\u0196\0\u01d0\0\u020a\0\u0244\0\256\0\u027e\0\u02b8"+
    "\0\u02f2\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488"+
    "\0\u04c2\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658"+
    "\0\u0692\0\u06cc\0\u0706\0\256\0\256\0\256\0\256\0\256"+
    "\0\256\0\256\0\256\0\256\0\256\0\u01d0\0\u0740\0\u015c"+
    "\0\u077a\0\u07b4\0\u07ee\0\256\0\u0828\0\u0862\0\256\0\u089c"+
    "\0\u0122\0\u08d6\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8\0\u0a32"+
    "\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8\0\256"+
    "\0\256\0\256\0\256\0\256\0\256\0\256\0\u0740\0\256"+
    "\0\u0c02\0\256\0\u0c3c\0\u0c76\0\256\0\256\0\u0122\0\u0122"+
    "\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c\0\u0e46"+
    "\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2\0\u0fdc\0\u1016"+
    "\0\u1050\0\u108a\0\256\0\u0122\0\u10c4\0\u10fe\0\u0122\0\u1138"+
    "\0\u0122\0\u1172\0\u11ac\0\u0122\0\u11e6\0\u1220\0\u125a\0\u1294"+
    "\0\u12ce\0\256\0\u0122\0\u1308\0\u1342\0\u137c\0\256\0\u0122"+
    "\0\u13b6\0\u13f0\0\u142a\0\u1464\0\256\0\u0122\0\u149e\0\256"+
    "\0\u0122\0\u0122\0\u14d8\0\u1512\0\u154c\0\u1586\0\u15c0\0\u15fa"+
    "\0\u1634\0\u166e\0\256\0\u16a8\0\u0122\0\u16e2\0\256\0\u0122"+
    "\0\u171c\0\u1756\0\256\0\u0122";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\3\5\1\6\1\7\1\4\1\10\1\11\1\4"+
    "\1\12\1\13\1\14\3\4\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\10\1\25\1\26\1\10"+
    "\1\27\1\30\2\10\1\31\1\32\4\10\1\33\1\34"+
    "\1\4\1\10\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\0\2\54\2\0\1\55\64\54\1\0\2\54"+
    "\3\0\6\54\1\56\55\54\100\0\1\7\1\57\70\0"+
    "\1\10\1\0\1\10\1\60\14\0\4\10\1\0\16\10"+
    "\1\0\1\10\31\0\1\10\60\0\13\61\1\0\56\61"+
    "\23\0\1\55\63\0\1\62\54\0\13\63\1\0\56\63"+
    "\22\0\1\64\62\0\1\65\7\0\1\66\74\0\1\67"+
    "\4\0\1\70\43\0\1\10\1\0\1\10\1\60\14\0"+
    "\1\10\1\71\2\10\1\0\1\10\1\72\14\10\1\0"+
    "\1\10\25\0\1\10\1\0\1\10\1\60\14\0\4\10"+
    "\1\0\4\10\1\73\4\10\1\74\4\10\1\0\1\10"+
    "\25\0\1\10\1\0\1\10\1\60\14\0\3\10\1\75"+
    "\1\0\16\10\1\0\1\10\54\0\1\76\42\0\1\10"+
    "\1\0\1\10\1\60\14\0\4\10\1\0\2\10\1\77"+
    "\13\10\1\0\1\10\25\0\1\10\1\0\1\10\1\60"+
    "\14\0\4\10\1\0\12\10\1\100\3\10\1\0\1\10"+
    "\25\0\1\10\1\0\1\10\1\60\14\0\4\10\1\0"+
    "\4\10\1\101\11\10\1\0\1\10\25\0\1\10\1\0"+
    "\1\10\1\60\14\0\4\10\1\0\4\10\1\102\5\10"+
    "\1\103\3\10\1\0\1\10\25\0\1\10\1\0\1\10"+
    "\1\60\14\0\4\10\1\0\4\10\1\104\3\10\1\105"+
    "\5\10\1\0\1\10\25\0\1\10\1\0\1\10\1\60"+
    "\14\0\4\10\1\0\12\10\1\106\3\10\1\0\1\10"+
    "\25\0\1\10\1\0\1\10\1\60\14\0\4\10\1\0"+
    "\10\10\1\107\5\10\1\0\1\10\72\0\1\110\73\0"+
    "\1\111\71\0\1\112\71\0\1\113\71\0\1\114\74\0"+
    "\1\115\72\0\1\116\16\0\1\117\64\0\12\61\1\120"+
    "\57\61\16\0\1\121\53\0\20\63\1\122\51\63\13\65"+
    "\1\123\56\65\3\66\1\124\1\125\65\66\34\0\1\126"+
    "\42\0\1\10\1\0\1\10\1\60\14\0\4\10\1\0"+
    "\2\10\1\127\13\10\1\0\1\10\25\0\1\10\1\0"+
    "\1\10\1\60\14\0\4\10\1\0\12\10\1\130\3\10"+
    "\1\0\1\10\25\0\1\10\1\0\1\10\1\60\14\0"+
    "\3\10\1\131\1\0\16\10\1\0\1\10\25\0\1\10"+
    "\1\0\1\10\1\60\14\0\4\10\1\132\1\133\15\10"+
    "\1\0\1\10\64\0\1\134\32\0\1\10\1\0\1\10"+
    "\1\60\14\0\4\10\1\0\12\10\1\135\3\10\1\0"+
    "\1\10\25\0\1\10\1\0\1\10\1\60\14\0\4\10"+
    "\1\0\5\10\1\136\10\10\1\0\1\10\25\0\1\10"+
    "\1\0\1\10\1\60\14\0\4\10\1\0\5\10\1\137"+
    "\10\10\1\0\1\10\25\0\1\10\1\0\1\10\1\60"+
    "\14\0\4\10\1\0\4\10\1\140\11\10\1\0\1\10"+
    "\25\0\1\10\1\0\1\10\1\60\14\0\2\10\1\141"+
    "\1\10\1\0\16\10\1\0\1\10\25\0\1\10\1\0"+
    "\1\10\1\60\14\0\4\10\1\0\1\10\1\142\14\10"+
    "\1\0\1\10\25\0\1\10\1\0\1\10\1\60\14\0"+
    "\4\10\1\0\11\10\1\143\4\10\1\0\1\10\25\0"+
    "\1\10\1\0\1\10\1\60\13\0\1\144\1\145\3\10"+
    "\1\0\16\10\1\0\1\10\25\0\1\10\1\0\1\10"+
    "\1\60\13\0\1\146\1\147\3\10\1\0\16\10\1\0"+
    "\1\10\20\0\13\150\1\0\56\150\13\65\1\123\7\65"+
    "\1\125\46\65\4\0\1\125\72\0\1\10\1\0\1\10"+
    "\1\60\14\0\4\10\1\151\1\152\15\10\1\0\1\10"+
    "\47\0\1\153\47\0\1\10\1\0\1\10\1\60\14\0"+
    "\2\10\1\154\1\10\1\0\16\10\1\0\1\10\44\0"+
    "\2\155\51\0\1\10\1\0\1\10\1\60\13\0\1\155"+
    "\1\156\3\10\1\0\16\10\1\0\1\10\25\0\1\10"+
    "\1\0\1\10\1\60\14\0\2\10\1\157\1\10\1\0"+
    "\16\10\1\0\1\10\25\0\1\10\1\0\1\10\1\60"+
    "\14\0\4\10\1\0\6\10\1\160\7\10\1\0\1\10"+
    "\25\0\1\10\1\0\1\10\1\60\14\0\3\10\1\161"+
    "\1\0\16\10\1\0\1\10\25\0\1\10\1\0\1\10"+
    "\1\60\14\0\4\10\1\0\11\10\1\162\4\10\1\0"+
    "\1\10\25\0\1\10\1\0\1\10\1\60\14\0\4\10"+
    "\1\0\2\10\1\163\13\10\1\0\1\10\25\0\1\10"+
    "\1\0\1\10\1\60\14\0\4\10\1\0\12\10\1\164"+
    "\3\10\1\0\1\10\53\0\1\165\43\0\1\10\1\0"+
    "\1\10\1\60\14\0\4\10\1\0\1\10\1\166\14\10"+
    "\1\0\1\10\50\0\1\167\46\0\1\10\1\0\1\10"+
    "\1\60\14\0\3\10\1\170\1\0\16\10\1\0\1\10"+
    "\20\0\14\150\1\171\55\150\27\0\1\172\47\0\1\10"+
    "\1\0\1\10\1\60\14\0\2\10\1\173\1\10\1\0"+
    "\16\10\1\0\1\10\53\0\1\174\43\0\1\10\1\0"+
    "\1\10\1\60\14\0\4\10\1\0\1\10\1\175\14\10"+
    "\1\0\1\10\25\0\1\10\1\0\1\10\1\60\14\0"+
    "\3\10\1\176\1\0\16\10\1\0\1\10\25\0\1\10"+
    "\1\0\1\10\1\60\14\0\4\10\1\0\16\10\1\177"+
    "\1\200\25\0\1\10\1\0\1\10\1\60\13\0\1\201"+
    "\1\202\3\10\1\0\16\10\1\0\1\10\54\0\1\203"+
    "\42\0\1\10\1\0\1\10\1\60\14\0\4\10\1\0"+
    "\2\10\1\204\13\10\1\0\1\10\47\0\1\205\47\0"+
    "\1\10\1\0\1\10\1\60\14\0\2\10\1\206\1\10"+
    "\1\0\16\10\1\0\1\10\20\0\14\150\1\171\1\207"+
    "\54\150\45\0\1\210\31\0\1\10\1\0\1\10\1\60"+
    "\14\0\4\10\1\0\13\10\1\211\2\10\1\0\1\10"+
    "\25\0\1\10\1\0\1\10\1\60\14\0\2\10\1\212"+
    "\1\10\1\0\16\10\1\0\1\10\53\0\1\213\43\0"+
    "\1\10\1\0\1\10\1\60\14\0\4\10\1\0\1\10"+
    "\1\214\14\10\1\0\1\10\50\0\1\215\12\0\1\216"+
    "\33\0\1\10\1\0\1\10\1\60\14\0\3\10\1\217"+
    "\1\0\11\10\1\220\4\10\1\0\1\10\20\0\14\150"+
    "\1\171\2\150\1\120\52\150\37\0\1\221\37\0\1\10"+
    "\1\0\1\10\1\60\14\0\4\10\1\0\5\10\1\222"+
    "\10\10\1\0\1\10\53\0\1\223\76\0\1\224\36\0"+
    "\1\10\1\0\1\10\1\60\14\0\4\10\1\0\1\10"+
    "\1\225\14\10\1\0\1\10\25\0\1\10\1\0\1\10"+
    "\1\60\14\0\4\10\1\0\6\10\1\226\7\10\1\0"+
    "\1\10\47\0\1\227\47\0\1\10\1\0\1\10\1\60"+
    "\14\0\2\10\1\230\1\10\1\0\16\10\1\0\1\10"+
    "\50\0\1\231\46\0\1\10\1\0\1\10\1\60\14\0"+
    "\3\10\1\232\1\0\16\10\1\0\1\10\47\0\1\233"+
    "\47\0\1\10\1\0\1\10\1\60\14\0\2\10\1\234"+
    "\1\10\1\0\16\10\1\0\1\10\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6032];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\3\11\7\1\1\11\25\1\12\11\1\1\5\0"+
    "\1\11\1\0\1\1\1\11\1\0\5\1\1\0\11\1"+
    "\7\11\1\1\1\11\1\0\1\11\1\0\1\1\2\11"+
    "\3\1\1\0\1\1\1\0\7\1\1\0\1\1\1\0"+
    "\1\1\2\0\1\1\1\11\1\1\1\0\7\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\11\1\1\1\0\2\1"+
    "\1\11\1\1\1\0\1\1\1\0\1\1\1\11\1\1"+
    "\1\0\1\11\2\1\1\0\1\1\2\0\2\1\1\0"+
    "\1\1\1\11\1\0\2\1\1\11\1\1\1\0\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public ArrayList<ErrorC> listaErrores = new ArrayList(); // Lista para almacenar errores.
    public ArrayList<lexema> listaLexemas = new ArrayList(); // Lista para almacenar el flujo de palabras (tokens).

    public void adderror(int linea, int columna, String valor)
    {        
        listaErrores.add(new ErrorC(ErrorC.TipoError.LEXICO,valor, linea, columna));
    }

    public void addLexema(String tipo, String valor, int linea, int columna)
    {        
        listaLexemas.add(new lexema(tipo, valor, linea, columna));	            
    } 
    public void Imprimir(String cadena)
    {
        System.out.println(cadena);
    }   
 



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return new Symbol(sym.EOF);    
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Caracter ilegal: " + yytext()+" Linea : "+yyline +" Columna: "+yychar); 
            adderror(yyline, yychar, yytext());
            }
          case 52: break;
          case 2: 
            { //Imprimir("Salto de linea");
            }
          case 53: break;
          case 3: 
            { yychar=0;
            }
          case 54: break;
          case 4: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.entero, yychar, yyline,Integer.parseInt(yytext()));
            }
          case 55: break;
          case 5: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.id, yychar, yyline, yytext().toLowerCase());
            }
          case 56: break;
          case 6: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.multi, yychar, yyline, yytext());
            }
          case 57: break;
          case 7: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.dospuntos, yychar, yyline, yytext());
            }
          case 58: break;
          case 8: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.menos, yychar, yyline, yytext());
            }
          case 59: break;
          case 9: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.div, yychar, yyline, yytext());
            }
          case 60: break;
          case 10: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.suma, yychar, yyline, yytext());
            }
          case 61: break;
          case 11: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.not, yychar, yyline, yytext());
            }
          case 62: break;
          case 12: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.igual, yychar, yyline, yytext());
            }
          case 63: break;
          case 13: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.mayor, yychar, yyline, yytext());
            }
          case 64: break;
          case 14: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.menor, yychar, yyline, yytext());
            }
          case 65: break;
          case 15: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.puntocoma, yychar, yyline, yytext());
            }
          case 66: break;
          case 16: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.pari, yychar, yyline, yytext());
            }
          case 67: break;
          case 17: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.pard, yychar, yyline, yytext());
            }
          case 68: break;
          case 18: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.interrogante, yychar, yyline, yytext());
            }
          case 69: break;
          case 19: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.llavei, yychar, yyline, yytext());
            }
          case 70: break;
          case 20: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.llaved, yychar, yyline, yytext());
            }
          case 71: break;
          case 21: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.modulo, yychar, yyline, yytext());
            }
          case 72: break;
          case 22: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.potencia, yychar, yyline, yytext());
            }
          case 73: break;
          case 23: 
            { /**/
            }
          case 74: break;
          case 24: 
            { yybegin(YYINITIAL);
            }
          case 75: break;
          case 25: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.decremento, yychar, yyline, yytext());
            }
          case 76: break;
          case 26: 
            { Imprimir(yytext());
            }
          case 77: break;
          case 27: 
            { addLexema("reservada", yytext(), yyline, yychar);
        return  new Symbol(sym.si, yychar, yyline, yytext());
            }
          case 78: break;
          case 28: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.aumento, yychar, yyline, yytext());
            }
          case 79: break;
          case 29: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.desigual, yychar, yyline, yytext());
            }
          case 80: break;
          case 30: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.igualigual, yychar, yyline, yytext());
            }
          case 81: break;
          case 31: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.mayorigual, yychar, yyline, yytext());
            }
          case 82: break;
          case 32: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.menorigual, yychar, yyline, yytext());
            }
          case 83: break;
          case 33: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.or, yychar, yyline, yytext());
            }
          case 84: break;
          case 34: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.and, yychar, yyline, yytext());
            }
          case 85: break;
          case 35: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.decimal, yychar, yyline,Double.parseDouble(yytext()));
            }
          case 86: break;
          case 36: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.cadena, yychar, yyline,yytext().substring(1, yytext().length()-1));
            }
          case 87: break;
          case 37: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.caracter, yychar, yyline,yytext().substring(1, yytext().length()-1).charAt(0));
            }
          case 88: break;
          case 38: 
            { addLexema("reservada", yytext(), yyline, yychar);            
            return  new Symbol(sym.tint, yychar, yyline, yytext());
            }
          case 89: break;
          case 39: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.para, yychar, yyline, yytext());
            }
          case 90: break;
          case 40: 
            { addLexema("reservada", yytext(), yyline, yychar);
        return  new Symbol(sym.sino, yychar, yyline, yytext());
            }
          case 91: break;
          case 41: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.booleano, yychar, yyline, true);
            }
          case 92: break;
          case 42: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.tbool, yychar, yyline, yytext());
            }
          case 93: break;
          case 43: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.tchar, yychar, yyline, yytext());
            }
          case 94: break;
          case 44: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.booleano, yychar, yyline, false);
            }
          case 95: break;
          case 45: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.romper, yychar, yyline, yytext());
            }
          case 96: break;
          case 46: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.mientras, yychar, yyline, yytext());
            }
          case 97: break;
          case 47: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.tstring, yychar, yyline, yytext());
            }
          case 98: break;
          case 48: 
            { addLexema("reservada", yytext(), yyline, yychar);            
            return  new Symbol(sym.tdouble, yychar, yyline, yytext());
            }
          case 99: break;
          case 49: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.print, yychar, yyline, yytext());
            }
          case 100: break;
          case 50: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.continuar, yychar, yyline, yytext());
            }
          case 101: break;
          case 51: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.printable, yychar, yyline, yytext());
            }
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
