/* The following code was generated by JFlex 1.6.1 */

package Analisis;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import Analisis.lexema;
import Utilidades.ErrorC;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>scanner.jflex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int cad1 = 2;
  public static final int cad2 = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    18, 18, 18, 18, 18, 18, 18, 18, 18,  1,  3, 68,  1,  2, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
     1, 47, 10, 18, 18, 66, 52, 11, 54, 55, 12, 46, 45, 19,  5, 21, 
     4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 17, 53, 50, 48, 49, 56, 
    18,  6,  6, 42, 60,  6,  6,  6,  6, 61,  6,  6, 41,  6,  6,  6, 
     6,  6,  6, 40,  6, 43,  6,  6,  6,  6,  6, 64, 18, 65, 67,  9, 
    18, 34, 31, 32, 28, 24, 23, 36, 33, 22,  6, 44, 25, 59, 20, 29, 
    37,  6, 35, 26, 27, 30, 38, 39, 58, 62,  6, 57, 51, 63, 18, 18, 
    18, 18, 18, 18, 18, 68, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18,  8, 18, 18, 18, 18, 18, 18, 18,  8, 18, 18, 18,  8, 18, 18, 
    18,  8, 18,  8, 18, 18, 18, 18, 18, 18,  8, 18, 18, 18, 18, 18, 
    18, 18, 18,  7, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 13, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\1\1\10\1\1\1\11\1\12\1\6\1\13"+
    "\16\6\1\14\1\15\1\16\1\17\1\20\1\21\2\1"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\4\0\1\36\1\0\1\6"+
    "\1\0\1\37\1\6\1\40\15\6\1\41\17\6\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\2\0\1\53\2\0\2\37\1\6\1\54\2\6\1\55"+
    "\4\6\1\56\12\6\1\57\15\6\1\60\6\6\3\0"+
    "\4\6\1\61\13\6\1\62\1\63\2\6\1\64\3\6"+
    "\1\65\1\66\11\6\1\67\2\6\1\0\2\6\1\70"+
    "\1\71\3\6\1\72\6\6\1\73\2\6\1\74\1\75"+
    "\1\6\1\76\3\6\1\77\1\6\1\100\2\6\1\101"+
    "\1\6\1\0\1\6\1\102\1\6\1\103\1\104\1\105"+
    "\2\6\1\106\3\6\1\107\2\6\1\110\1\6\1\111"+
    "\6\6\1\112\4\6\1\113\3\6\1\114\1\6\1\115"+
    "\3\6\1\116\2\6\1\117\1\120\1\121\7\6\1\122"+
    "\1\123\1\124\1\6\1\125\2\6\1\126\1\127\1\130";

  private static int [] zzUnpackAction() {
    int [] result = new int[285];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\322\0\322\0\322\0\u0118\0\322"+
    "\0\u015e\0\u01a4\0\322\0\u01ea\0\322\0\u0230\0\322\0\u0276"+
    "\0\u02bc\0\u0302\0\u0348\0\u038e\0\u03d4\0\u041a\0\u0460\0\u04a6"+
    "\0\u04ec\0\u0532\0\u0578\0\u05be\0\u0604\0\u064a\0\u0690\0\u06d6"+
    "\0\322\0\u071c\0\u0762\0\u07a8\0\u07ee\0\u0834\0\u087a\0\u08c0"+
    "\0\322\0\322\0\322\0\322\0\322\0\322\0\322\0\322"+
    "\0\322\0\322\0\322\0\322\0\u0906\0\u01a4\0\u094c\0\u0992"+
    "\0\322\0\u09d8\0\u0a1e\0\u0a64\0\u0aaa\0\u0af0\0\u015e\0\u0b36"+
    "\0\u0b7c\0\u0bc2\0\u0c08\0\u0c4e\0\u0c94\0\u0cda\0\u0d20\0\u0d66"+
    "\0\u0dac\0\u0df2\0\u0e38\0\u0e7e\0\u0ec4\0\u0f0a\0\u0f50\0\u0f96"+
    "\0\u0fdc\0\u1022\0\u1068\0\u10ae\0\u10f4\0\u113a\0\u1180\0\u11c6"+
    "\0\u120c\0\u1252\0\u1298\0\u12de\0\322\0\322\0\322\0\322"+
    "\0\322\0\322\0\322\0\u0906\0\322\0\u1324\0\u136a\0\u015e"+
    "\0\u13b0\0\u13f6\0\u143c\0\322\0\u1482\0\u015e\0\u14c8\0\u150e"+
    "\0\u015e\0\u1554\0\u159a\0\u15e0\0\u1626\0\u166c\0\u16b2\0\u16f8"+
    "\0\u173e\0\u1784\0\u17ca\0\u1810\0\u1856\0\u189c\0\u18e2\0\u1928"+
    "\0\u015e\0\u196e\0\u19b4\0\u19fa\0\u1a40\0\u1a86\0\u1acc\0\u1b12"+
    "\0\u1b58\0\u1b9e\0\u1be4\0\u1c2a\0\u1c70\0\u1cb6\0\u015e\0\u1cfc"+
    "\0\u1d42\0\u1d88\0\u1dce\0\u1e14\0\u1e5a\0\u1ea0\0\u1ee6\0\u1f2c"+
    "\0\u1f72\0\u1fb8\0\u1ffe\0\u2044\0\u015e\0\u208a\0\u20d0\0\u2116"+
    "\0\u215c\0\u21a2\0\u21e8\0\u222e\0\u2274\0\u22ba\0\u2300\0\u2346"+
    "\0\u015e\0\u015e\0\u238c\0\u23d2\0\u015e\0\u2418\0\u245e\0\u24a4"+
    "\0\u015e\0\u015e\0\u24ea\0\u2530\0\u2576\0\u25bc\0\u2602\0\u2648"+
    "\0\u268e\0\u26d4\0\u271a\0\u015e\0\u2760\0\u27a6\0\u27ec\0\u2832"+
    "\0\u2878\0\u015e\0\u015e\0\u28be\0\u2904\0\u294a\0\u015e\0\u2990"+
    "\0\u29d6\0\u2a1c\0\u2a62\0\u2aa8\0\u2aee\0\u015e\0\u2b34\0\u2b7a"+
    "\0\u015e\0\u015e\0\u2bc0\0\u015e\0\u2c06\0\u2c4c\0\u2c92\0\u015e"+
    "\0\u2cd8\0\u2d1e\0\u2d64\0\u2daa\0\u015e\0\u2df0\0\u2e36\0\u2e7c"+
    "\0\u015e\0\u2ec2\0\u015e\0\u015e\0\u015e\0\u2f08\0\u2f4e\0\u015e"+
    "\0\u2f94\0\u2fda\0\u3020\0\u015e\0\u3066\0\u30ac\0\u015e\0\u30f2"+
    "\0\u015e\0\u3138\0\u317e\0\u31c4\0\u320a\0\u3250\0\u3296\0\u015e"+
    "\0\u32dc\0\u3322\0\u3368\0\u33ae\0\u015e\0\u33f4\0\u343a\0\u3480"+
    "\0\u015e\0\u34c6\0\u015e\0\u350c\0\u3552\0\u3598\0\u015e\0\u35de"+
    "\0\u3624\0\u015e\0\u015e\0\u015e\0\u366a\0\u36b0\0\u36f6\0\u373c"+
    "\0\u3782\0\u37c8\0\u380e\0\u015e\0\u015e\0\u015e\0\u3854\0\u015e"+
    "\0\u389a\0\u38e0\0\u015e\0\u015e\0\u015e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[285];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\6\1\7\1\10\1\11\1\12\1\4"+
    "\1\11\1\13\1\14\1\15\1\16\3\4\1\17\1\4"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\11\1\26"+
    "\1\27\1\30\2\11\1\31\1\32\1\11\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\5\11\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\5\11\1\56\1\57\1\60\1\61\1\62"+
    "\3\0\15\63\3\0\64\63\2\0\15\64\3\0\64\64"+
    "\113\0\1\7\1\65\104\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\27\11\15\0\5\11"+
    "\17\0\1\11\75\0\14\67\1\0\71\67\16\0\1\70"+
    "\112\0\1\71\66\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\72\2\11\1\73\24\11\15\0"+
    "\5\11\23\0\1\74\10\0\1\75\64\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\76\1\0\1\11"+
    "\1\77\25\11\15\0\1\11\1\100\3\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\1\101\6\11\1\102\4\11\1\103\12\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\3\11\1\104\23\11\15\0\1\105\4\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\5\11\1\106\2\11\1\107\10\11\1\110"+
    "\5\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\7\11\1\111\3\11"+
    "\1\112\1\11\1\113\11\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\2\11\1\114\4\11\1\115\17\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\7\11\1\116\5\11\1\117\11\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\3\11\1\120\3\11\1\121\3\11\1\122"+
    "\1\123\12\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\11\11\1\124"+
    "\15\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\2\11\1\125\24\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\15\11\1\126\11\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\7\11\1\127\1\130\4\11\1\131"+
    "\11\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\7\11\1\132\17\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\13\11\1\133\1\11\1\134"+
    "\11\11\15\0\5\11\65\0\1\135\107\0\1\136\105\0"+
    "\1\137\105\0\1\140\105\0\1\141\110\0\1\142\106\0"+
    "\1\143\25\0\1\144\101\0\13\67\1\145\72\67\17\0"+
    "\1\146\102\0\1\147\75\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\21\11\1\150\5\11"+
    "\15\0\5\11\7\0\14\151\1\152\71\151\2\75\1\153"+
    "\1\154\102\75\4\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\4\11\1\155\1\156\21\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\17\11\1\157\7\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\160\1\0\27\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\15\11\1\161\11\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\3\11"+
    "\1\162\23\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\4\11\1\163"+
    "\22\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\5\11\1\164\21\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\14\11\1\165\1\166\11\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\17\11\1\167\7\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\1\170\26\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\22\11\1\171\1\172\1\173\1\174\1\11\15\0"+
    "\2\11\1\175\1\176\1\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\1\177\26\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\10\11\1\200\16\11\15\0"+
    "\4\11\1\201\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\1\11\1\202\25\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\10\11\1\203\16\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\7\11\1\204\17\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\2\11\1\205\24\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\14\11\1\206\12\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\207\1\0\27\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\14\11\1\210\12\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\4\11\1\211\1\212\21\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\4\11\1\213\22\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\5\11\1\214\6\11\1\215\12\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\14\11\1\216\12\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\21\11\1\217\5\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\11\11\1\220\15\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\1\221\6\11\1\222\17\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\1\223\26\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\1\224\26\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\1\225\26\11\15\0\5\11"+
    "\7\0\14\226\1\0\71\226\14\0\1\227\71\0\14\151"+
    "\1\230\71\151\14\0\1\152\10\0\1\154\63\0\1\154"+
    "\106\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\5\11\1\231\21\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\7\11\1\232\17\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\14\11\1\233\12\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\4\11"+
    "\1\234\22\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\2\11\1\235"+
    "\24\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\2\11\1\236\24\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\5\11\1\237\21\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\1\240\26\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\2\11\1\241\24\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\5\11\1\242\21\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\5\11"+
    "\1\243\21\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\7\11\1\244"+
    "\17\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\13\11\1\245\13\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\17\11\1\246\7\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\7\11\1\247\17\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\250\1\0\27\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\4\11"+
    "\1\251\22\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\2\11\1\252"+
    "\24\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\14\11\1\253\12\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\11\11\1\254\15\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\3\11\1\255\23\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\14\11\1\256\12\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\4\11\1\257\22\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\5\11\1\260\21\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\15\11"+
    "\1\261\11\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\2\11\1\262"+
    "\24\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\12\11\1\263\14\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\5\11\1\264\21\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\10\11\1\265\16\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\6\11\1\266\20\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\17\11\1\267\7\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\3\11\1\270\23\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\271\1\0\20\11"+
    "\1\272\6\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\5\11\1\273"+
    "\21\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\6\11\1\274\20\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\3\11\1\275\23\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\5\11\1\276\21\11\15\0\5\11"+
    "\7\0\15\226\1\277\70\226\14\151\1\227\10\151\1\0"+
    "\74\151\1\230\10\151\1\154\60\151\4\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\14\11"+
    "\1\300\12\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\15\11\1\301"+
    "\11\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\3\11\1\302\23\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\2\11\1\303\24\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\304\1\0\27\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\1\305\26\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\306\1\0\27\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\15\11\1\307\11\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\12\11\1\310\14\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\15\11\1\311\11\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\21\11\1\312\5\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\14\11"+
    "\1\313\12\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\17\11\1\314"+
    "\7\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\10\11\1\315\16\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\5\11\1\316\21\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\10\11\1\317\16\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\3\11\1\320\23\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\26\11\1\321\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\4\11"+
    "\1\322\22\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\1\323\26\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\13\11\1\324\13\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\15\11\1\325\11\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\15\11\1\326\11\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\327\12\0\1\11"+
    "\1\0\27\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\13\11\1\330"+
    "\13\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\1\331\26\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\5\11\1\332\21\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\14\11\1\333\12\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\2\11\1\334\24\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\2\11\1\335\24\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\2\11"+
    "\1\336\24\11\15\0\5\11\7\0\15\226\1\277\1\337"+
    "\67\226\4\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\340\1\0\27\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\5\11\1\341\21\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\6\11"+
    "\1\342\20\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\12\11\1\343"+
    "\14\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\16\11\1\344\10\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\13\11\1\345\13\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\1\346\26\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\2\11\1\347\24\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\15\11\1\350\11\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\2\11"+
    "\1\351\24\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\11\11\1\352"+
    "\15\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\3\11\1\353\23\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\2\11\1\354\24\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\355\1\0\27\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\14\11\1\356\12\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\357\1\0\27\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\1\11\1\360\25\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\12\11\1\361\14\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\3\11\1\362\10\11\1\363\12\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\5\11\1\364\21\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\12\11\1\365\14\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\366\12\0\1\11"+
    "\1\0\27\11\15\0\5\11\7\0\15\226\1\277\2\226"+
    "\1\145\65\226\4\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\12\11\1\367\14\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\4\11\1\370\22\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\371\1\0\27\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\15\11"+
    "\1\372\11\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\15\11\1\373"+
    "\11\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\3\11\1\374\23\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\5\11\1\375\21\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\10\11\1\376\16\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\12\11\1\377\14\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\1\u0100\26\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\u0101\1\0\27\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\11\11\1\u0102\15\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\2\11\1\u0103\24\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\5\11\1\u0104\21\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\1\11\1\u0105\25\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\2\11\1\u0106\24\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\16\11"+
    "\1\u0107\10\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\24\11\1\u0108"+
    "\2\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\24\11\1\u0109\2\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\2\11\1\u010a\24\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\2\11\1\u010b\24\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\5\11\1\u010c\21\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\3\11\1\u010d\23\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\3\11\1\u010e\23\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\2\11"+
    "\1\u010f\24\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\1\u0110\26\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\7\11\1\u0111\17\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\14\11\1\u0112\12\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\14\11\1\u0113\12\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\2\11\1\u0114\24\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\2\11\1\u0115\24\11\15\0\5\11\13\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\12\0\1\11\1\0\6\11"+
    "\1\u0116\20\11\15\0\5\11\13\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\12\0\1\11\1\0\3\11\1\u0117"+
    "\23\11\15\0\5\11\13\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\12\0\1\11\1\0\1\11\1\u0118\25\11"+
    "\15\0\5\11\13\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\12\0\1\11\1\0\4\11\1\u0119\22\11\15\0"+
    "\5\11\13\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\12\0\1\11\1\0\4\11\1\u011a\22\11\15\0\5\11"+
    "\13\0\1\11\1\0\1\11\1\66\1\0\1\11\12\0"+
    "\1\11\1\0\2\11\1\u011b\24\11\15\0\5\11\13\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\12\0\1\11"+
    "\1\0\2\11\1\u011c\24\11\15\0\5\11\13\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\12\0\1\11\1\0"+
    "\2\11\1\u011d\24\11\15\0\5\11\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14630];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\3\11\1\1\1\11\2\1\1\11\1\1\1\11"+
    "\1\1\1\11\21\1\1\11\7\1\14\11\4\0\1\11"+
    "\1\0\1\1\1\0\40\1\7\11\1\1\1\11\2\0"+
    "\1\1\2\0\1\1\1\11\51\1\3\0\46\1\1\0"+
    "\37\1\1\0\76\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[285];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public ArrayList<ErrorC> listaErrores = new ArrayList(); // Lista para almacenar errores.
    public ArrayList<lexema> listaLexemas = new ArrayList(); // Lista para almacenar el flujo de palabras (tokens).
    public String cadena ="";
    public int linea=0,columna = 0;
    public void adderror(int linea, int columna, String valor)
    {        
        listaErrores.add(new ErrorC(ErrorC.TipoError.LEXICO,valor, linea, columna));
    }

    public void addLexema(String tipo, String valor, int linea, int columna)
    {        
        listaLexemas.add(new lexema(tipo, valor, linea, columna));	            
    } 
    public void Imprimir(String cadena)
    {
        System.out.println(cadena);
    }   
 



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return new Symbol(sym.EOF);    
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Caracter ilegal: " + yytext()+" Linea : "+yyline +" Columna: "+yychar); 
            adderror(yyline, yychar, yytext());
            }
          case 89: break;
          case 2: 
            { //Imprimir("Salto de linea");
            }
          case 90: break;
          case 3: 
            { yychar=0;
            }
          case 91: break;
          case 4: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	  
            if(Long.parseLong(yytext())> Utilidades.Singlenton.maxInt && Long.parseLong(yytext()) < Utilidades.Singlenton.minInt )
            {
                Utilidades.Singlenton.registrarError("Entero", "Número entero demasiado grande", ErrorC.TipoError.SEMANTICO,yyline, yychar);
                return new Symbol(sym.entero, yychar, yyline,0);             
            }   
            return new Symbol(sym.entero, yychar, yyline,Integer.parseInt(yytext()));
            }
          case 92: break;
          case 5: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.punto, yychar, yyline, yytext());
            }
          case 93: break;
          case 6: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.id, yychar, yyline, yytext().toLowerCase());
            }
          case 94: break;
          case 7: 
            { cadena = "";                    
            yybegin(cad1);
            linea = yyline;
            columna = yychar;
            }
          case 95: break;
          case 8: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.multi, yychar, yyline, yytext());
            }
          case 96: break;
          case 9: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.dospuntos, yychar, yyline, yytext());
            }
          case 97: break;
          case 10: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.menos, yychar, yyline, yytext());
            }
          case 98: break;
          case 11: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.div, yychar, yyline, yytext());
            }
          case 99: break;
          case 12: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.coma, yychar, yyline, yytext());
            }
          case 100: break;
          case 13: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.suma, yychar, yyline, yytext());
            }
          case 101: break;
          case 14: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.not, yychar, yyline, yytext());
            }
          case 102: break;
          case 15: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.igual, yychar, yyline, yytext());
            }
          case 103: break;
          case 16: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.mayor, yychar, yyline, yytext());
            }
          case 104: break;
          case 17: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.menor, yychar, yyline, yytext());
            }
          case 105: break;
          case 18: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.puntocoma, yychar, yyline, yytext());
            }
          case 106: break;
          case 19: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.pari, yychar, yyline, yytext());
            }
          case 107: break;
          case 20: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.pard, yychar, yyline, yytext());
            }
          case 108: break;
          case 21: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.interrogante, yychar, yyline, yytext());
            }
          case 109: break;
          case 22: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.llavei, yychar, yyline, yytext());
            }
          case 110: break;
          case 23: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.llaved, yychar, yyline, yytext());
            }
          case 111: break;
          case 24: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.corchetei, yychar, yyline, yytext());
            }
          case 112: break;
          case 25: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.corcheted, yychar, yyline, yytext());
            }
          case 113: break;
          case 26: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.modulo, yychar, yyline, yytext());
            }
          case 114: break;
          case 27: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.xor, yychar, yyline, yytext());
            }
          case 115: break;
          case 28: 
            { switch(yytext())
        {
            case "\\":          
                yybegin(cad2);
            break;
            case "\"":      
                yybegin(YYINITIAL);
                return new Symbol(sym.cadena, columna, linea ,cadena);             
            default:
                cadena += yytext();
            break;                
        }
            }
          case 116: break;
          case 29: 
            { switch(yytext())
        {
            case "\'":
                cadena += "\'";
            break;            
            case "\"":
                cadena += "\"";
            break;  
            case "?":
                cadena += "?";
            break;
            case "\\":
                cadena += "\\";
            break;  
            case "0":                
            break;  
            case "a":                
            break;   
            case "b":                
                cadena = cadena.substring(0, cadena.length()-1);
            break; 
            case "v":   
                String partes[] = cadena.split("\n");
                String subcadena = "";
                for(int i = 0 ; i < partes.length-1; i++)
                {
                    subcadena += partes[i];
                }         
                String tabulaciones[] = partes[partes.length].split("\t");
                for(int i = 0; i< tabulaciones.length; i++)
                {
                    subcadena += "\t";
                }
                cadena = subcadena;                                                       
            break;             
            case "n":                
                cadena = cadena + "\n";
            break; 
            case "t":                
                cadena = cadena + "\t";
            break;             
            case "r":       
                partes = cadena.split("\n");
                subcadena = "";
                for(int i = 0 ; i < partes.length-1; i++)
                {
                    subcadena += partes[i];
                }                                       
                cadena = subcadena;
            break;                                                                                                       
            default:
                Utilidades.Singlenton.registrarError("\\"+yytext(), "Carácter ilegal. Ha sido eliminado.", ErrorC.TipoError.SEMANTICO,yyline, yychar);
            break;                
        }
        yybegin(cad1);
            }
          case 117: break;
          case 30: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.decremento, yychar, yyline, yytext());
            }
          case 118: break;
          case 31: 
            { Imprimir(yytext());
            }
          case 119: break;
          case 32: 
            { addLexema("reservada", yytext(), yyline, yychar);
        return  new Symbol(sym.si, yychar, yyline, yytext());
            }
          case 120: break;
          case 33: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.hacer, yychar, yyline, yytext());
            }
          case 121: break;
          case 34: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.aumento, yychar, yyline, yytext());
            }
          case 122: break;
          case 35: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.desigual, yychar, yyline, yytext());
            }
          case 123: break;
          case 36: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.igualigual, yychar, yyline, yytext());
            }
          case 124: break;
          case 37: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.mayorigual, yychar, yyline, yytext());
            }
          case 125: break;
          case 38: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.menorigual, yychar, yyline, yytext());
            }
          case 126: break;
          case 39: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.or, yychar, yyline, yytext());
            }
          case 127: break;
          case 40: 
            { addLexema("simbolo", yytext(), yyline, yychar);  	        
            return new Symbol(sym.and, yychar, yyline, yytext());
            }
          case 128: break;
          case 41: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.decimal, yychar, yyline,Double.parseDouble(yytext()));
            }
          case 129: break;
          case 42: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.caracter, yychar, yyline,yytext().substring(1, yytext().length()-1).charAt(0));
            }
          case 130: break;
          case 43: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.nuevo, yychar, yyline, yytext());
            }
          case 131: break;
          case 44: 
            { addLexema("reservada", yytext(), yyline, yychar);            
            return  new Symbol(sym.tint, yychar, yyline, yytext());
            }
          case 132: break;
          case 45: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.para, yychar, yyline, yytext());
            }
          case 133: break;
          case 46: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.tstring, yychar, yyline, yytext());
            }
          case 134: break;
          case 47: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.try_, yychar, yyline, yytext());
            }
          case 135: break;
          case 48: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.potencia, yychar, yyline, yytext());
            }
          case 136: break;
          case 49: 
            { addLexema("reservada", yytext(), yyline, yychar);
        return  new Symbol(sym.sino, yychar, yyline, yytext());
            }
          case 137: break;
          case 50: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.este, yychar, yyline, yytext());
            }
          case 138: break;
          case 51: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.booleano, yychar, yyline, true);
            }
          case 139: break;
          case 52: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.tbool, yychar, yyline, yytext());
            }
          case 140: break;
          case 53: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.tchar, yychar, yyline, yytext());
            }
          case 141: break;
          case 54: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.caso, yychar, yyline, yytext());
            }
          case 142: break;
          case 55: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.tvoid, yychar, yyline, false);
            }
          case 143: break;
          case 56: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.final_, yychar, yyline, yytext());
            }
          case 144: break;
          case 57: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.booleano, yychar, yyline, false);
            }
          case 145: break;
          case 58: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.super_, yychar, yyline, yytext());
            }
          case 146: break;
          case 59: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.toint, yychar, yyline, yytext());
            }
          case 147: break;
          case 60: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.romper, yychar, yyline, yytext());
            }
          case 148: break;
          case 61: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.clase, yychar, yyline, yytext());
            }
          case 149: break;
          case 62: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.cat, yychar, yyline, yytext());
            }
          case 150: break;
          case 63: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.graph, yychar, yyline, yytext());
            }
          case 151: break;
          case 64: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.print, yychar, yyline, yytext());
            }
          case 152: break;
          case 65: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.mientras, yychar, yyline, yytext());
            }
          case 153: break;
          case 66: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.importar, yychar, yyline, yytext());
            }
          case 154: break;
          case 67: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.estatico, yychar, yyline, yytext());
            }
          case 155: break;
          case 68: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.tstring, yychar, yyline, yytext());
            }
          case 156: break;
          case 69: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.switch_, yychar, yyline, yytext());
            }
          case 157: break;
          case 70: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.tochar, yychar, yyline, yytext());
            }
          case 158: break;
          case 71: 
            { addLexema("reservada", yytext(), yyline, yychar);            
            return  new Symbol(sym.tdouble, yychar, yyline, yytext());
            }
          case 159: break;
          case 72: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.retorno, yychar, yyline, yytext());
            }
          case 160: break;
          case 73: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.publico, yychar, yyline, yytext());
            }
          case 161: break;
          case 74: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.extiende, yychar, yyline, yytext());
            }
          case 162: break;
          case 75: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.defecto, yychar, yyline, yytext());
            }
          case 163: break;
          case 76: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.println, yychar, yyline, yytext());
            }
          case 164: break;
          case 77: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.privado, yychar, yyline, yytext());
            }
          case 165: break;
          case 78: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.tostring, yychar, yyline, yytext());
            }
          case 166: break;
          case 79: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.todouble, yychar, yyline, yytext());
            }
          case 167: break;
          case 80: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.continuar, yychar, yyline, yytext());
            }
          case 168: break;
          case 81: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.abstracto, yychar, yyline, yytext());
            }
          case 169: break;
          case 82: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.leerarchivo, yychar, yyline, yytext());
            }
          case 170: break;
          case 83: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.printable, yychar, yyline, yytext());
            }
          case 171: break;
          case 84: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.protegido, yychar, yyline, yytext());
            }
          case 172: break;
          case 85: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.instanceof_, yychar, yyline, yytext());
            }
          case 173: break;
          case 86: 
            { addLexema("simbolo", yytext(), yyline, yychar);
            return new Symbol(sym.escribir, yychar, yyline, yytext());
            }
          case 174: break;
          case 87: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.tolower, yychar, yyline, yytext());
            }
          case 175: break;
          case 88: 
            { addLexema("reservada", yytext(), yyline, yychar);
            return  new Symbol(sym.touper, yychar, yyline, yytext());
            }
          case 176: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
