
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menos = 72;
  public static final int menor = 22;
  public static final int punto = 61;
  public static final int booleano = 82;
  public static final int decremento = 60;
  public static final int leerarchivo = 43;
  public static final int print = 16;
  public static final int tchar = 4;
  public static final int suma = 71;
  public static final int importar = 36;
  public static final int tochar = 48;
  public static final int println = 17;
  public static final int tvoid = 26;
  public static final int aumento = 59;
  public static final int div = 74;
  public static final int romper = 55;
  public static final int cadena = 78;
  public static final int dospuntos = 58;
  public static final int menorigual = 23;
  public static final int mientras = 53;
  public static final int abstracto = 27;
  public static final int privado = 39;
  public static final int sino = 67;
  public static final int tint = 2;
  public static final int toint = 50;
  public static final int decimal = 81;
  public static final int caso = 28;
  public static final int try_ = 51;
  public static final int sinosi = 66;
  public static final int llavei = 8;
  public static final int or = 64;
  public static final int caracter = 79;
  public static final int llaved = 9;
  public static final int extiende = 33;
  public static final int mayorigual = 24;
  public static final int nuevo = 38;
  public static final int tolower = 69;
  public static final int id = 12;
  public static final int retorno = 42;
  public static final int estatico = 44;
  public static final int desigual = 20;
  public static final int cat = 29;
  public static final int protegido = 40;
  public static final int puntocoma = 7;
  public static final int and = 63;
  public static final int mayor = 21;
  public static final int printable = 76;
  public static final int xor = 75;
  public static final int tbool = 5;
  public static final int EOF = 0;
  public static final int escribir = 52;
  public static final int super_ = 45;
  public static final int tstring = 6;
  public static final int este = 47;
  public static final int tostring = 68;
  public static final int publico = 41;
  public static final int potencia = 25;
  public static final int corchetei = 13;
  public static final int touper = 70;
  public static final int multi = 73;
  public static final int interrogante = 57;
  public static final int error = 1;
  public static final int switch_ = 46;
  public static final int corcheted = 14;
  public static final int continuar = 56;
  public static final int si = 65;
  public static final int entero = 80;
  public static final int graph = 35;
  public static final int pari = 10;
  public static final int hacer = 32;
  public static final int defecto = 31;
  public static final int igualigual = 19;
  public static final int pard = 11;
  public static final int para = 54;
  public static final int tdouble = 3;
  public static final int coma = 18;
  public static final int instanceof_ = 37;
  public static final int modulo = 77;
  public static final int not = 62;
  public static final int final_ = 34;
  public static final int igual = 15;
  public static final int todouble = 49;
  public static final int clase = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tint",
  "tdouble",
  "tchar",
  "tbool",
  "tstring",
  "puntocoma",
  "llavei",
  "llaved",
  "pari",
  "pard",
  "id",
  "corchetei",
  "corcheted",
  "igual",
  "print",
  "println",
  "coma",
  "igualigual",
  "desigual",
  "mayor",
  "menor",
  "menorigual",
  "mayorigual",
  "potencia",
  "tvoid",
  "abstracto",
  "caso",
  "cat",
  "clase",
  "defecto",
  "hacer",
  "extiende",
  "final_",
  "graph",
  "importar",
  "instanceof_",
  "nuevo",
  "privado",
  "protegido",
  "publico",
  "retorno",
  "leerarchivo",
  "estatico",
  "super_",
  "switch_",
  "este",
  "tochar",
  "todouble",
  "toint",
  "try_",
  "escribir",
  "mientras",
  "para",
  "romper",
  "continuar",
  "interrogante",
  "dospuntos",
  "aumento",
  "decremento",
  "punto",
  "not",
  "and",
  "or",
  "si",
  "sinosi",
  "sino",
  "tostring",
  "tolower",
  "touper",
  "suma",
  "menos",
  "multi",
  "div",
  "xor",
  "printable",
  "modulo",
  "cadena",
  "caracter",
  "entero",
  "decimal",
  "booleano"
  };
}

