
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int continuar = 24;
  public static final int igualigual = 15;
  public static final int suma = 35;
  public static final int romper = 23;
  public static final int printable = 40;
  public static final int interrogante = 25;
  public static final int igual = 13;
  public static final int llavei = 8;
  public static final int tbool = 5;
  public static final int sinosi = 33;
  public static final int caracter = 43;
  public static final int llaved = 9;
  public static final int tint = 2;
  public static final int si = 32;
  public static final int mientras = 21;
  public static final int pari = 10;
  public static final int menos = 36;
  public static final int menor = 18;
  public static final int EOF = 0;
  public static final int aumento = 27;
  public static final int pard = 11;
  public static final int para = 22;
  public static final int error = 1;
  public static final int mayor = 17;
  public static final int tstring = 6;
  public static final int entero = 44;
  public static final int or = 31;
  public static final int menorigual = 19;
  public static final int dospuntos = 26;
  public static final int desigual = 16;
  public static final int potencia = 39;
  public static final int id = 12;
  public static final int multi = 37;
  public static final int mayorigual = 20;
  public static final int and = 30;
  public static final int decremento = 28;
  public static final int not = 29;
  public static final int booleano = 46;
  public static final int puntocoma = 7;
  public static final int print = 14;
  public static final int tdouble = 3;
  public static final int div = 38;
  public static final int decimal = 45;
  public static final int modulo = 41;
  public static final int cadena = 42;
  public static final int sino = 34;
  public static final int tchar = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tint",
  "tdouble",
  "tchar",
  "tbool",
  "tstring",
  "puntocoma",
  "llavei",
  "llaved",
  "pari",
  "pard",
  "id",
  "igual",
  "print",
  "igualigual",
  "desigual",
  "mayor",
  "menor",
  "menorigual",
  "mayorigual",
  "mientras",
  "para",
  "romper",
  "continuar",
  "interrogante",
  "dospuntos",
  "aumento",
  "decremento",
  "not",
  "and",
  "or",
  "si",
  "sinosi",
  "sino",
  "suma",
  "menos",
  "multi",
  "div",
  "potencia",
  "printable",
  "modulo",
  "cadena",
  "caracter",
  "entero",
  "decimal",
  "booleano"
  };
}

